INSERT INTO BOOK (title,author,isbn) VALUES ('CEM ANOS DE SOLIDÃO','GABRIEL GARCÍA MÁRQUEZ','123');
INSERT INTO BOOK (title,author,isbn) VALUES ('CRIME E CASTIGO','FIÓDOR DOSTOYEVSKI','124');
INSERT INTO BOOK (title,author,isbn) VALUES ('ORGULHO E PRECONCEITO','JANE AUSTEN','125');
INSERT INTO BOOK (title,author,isbn) VALUES ('O SENHOR DOS ANÉIS','J.R.R. TOLKIEN','126');
INSERT INTO BOOK (title,author,isbn) VALUES ('DOM QUIXOTE DE LA MANCHA','MIGUEL DE CERVANTES','127');
INSERT INTO BOOK (title,author,isbn) VALUES ('O PEQUENO PRÍNCIPE','ANTOINE DE SAINT-EXUPÉRY','128');